baseURL = 'https://m4rti.dev'
languageCode = 'en-us'
title = 'Martí Comas'

[params]
favicon = "/favicon.ico"
relatedtext = "Related"
#list items
datesinlist = true
authorsinlist = true

#footer items
nextprev = true
taglist = true
showrss = true
